spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/filmecatalogo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

tmdb.api.key=c8f955abf5a429c68bb3eacddffd4efa
tmdb.api.url=https://api.themoviedb.org/3












